### ISSUE TITLE
A 1x1 Chunk Loader will load chunk(s) immediately around it

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [BG-Software-LLC/WildLoaders#18]
**Minecraft's Version**
(is a test server)
Paper version git-Paper-750 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
Dev build: Number 13 19/06/2021 10:46:03 from wiki

**Describe the bug**
I have this chunk loader that should only be loading a single chunk:
```
chunkloaders:
  1x1_loader:
    time: 86400
    type: BEACON
    name: '&6Chunk Loader &7(Place to load)'
    chunks-radius: 0 # This will load all chunks in a radius of 0, aka 1x1 chunks
    lore:
      - '&7Place this chunk loader to keep'
      - '&7the chunk loaded in the next {}!'
```

But when I place spawners in that chunk and 2 chunks right next to it, the chunk east of the loaded chunk also has a spawner spawning mobs. I made sure I did not confuse them with natural spawns by using Ravager spawners and I am not activating the spawners because I'm ~100 blocks above them.

In other words, it is loading at least 2 chunks. Strangely, the chunk north of the loaded chunk does not spawn mobs. 

**To Reproduce**
1. Create the chunk loader above.
2. Get the loader & place it in a chunk.
3. Place 1 Ravager spawner in the loaded chunk, and 1 in each chunk immediately around the spawner (North, South, East, West) (about center in each of the chunks). Note: I only tested North & East. 
3. Ensure the terrain is flat around the spawners (in all chunks) so the mobs spawn.
4. Fly up 100+ blocks into the sky. Make sure your render distance is high enough to see the mobs.
5. Set it to night (/night).
6. /killall all (with EssentialsX) to ensure you don't confuse which chunks mobs have spawned in.
7. Wait for mobs to spawn. Watch for like 5-10 min. My tests varied- One time it was slow (but still worked) in a chunk outside the loaded chunk. Another time it was faster than in the loaded chunk.

**Additional information**
I have a basic server setup I use for testing. This is what I used while testing this plugin. If you'd like to test it with the same plugins as me then you may download it here:
https://drive.google.com/file/d/1TSKMAtDrL9OtgfjnpGg0KHO9LKlThTZz/view?usp=sharing
It is on MC-Market as well.

**Comment by PiggiesGoSqueal** [comment]
I just tested it with the normal_loader that comes with the plugin. This same issue occurs.

```
  normal_loader:
    time: 86400
    type: BEACON
    name: '&6Chunk Loader &7(Place to load)'
    lore:
      - '&7Place this chunk loader to keep'
      - '&7the chunk loaded in the next {}!'
```
